// Provenance strip — the "receipts" that make the numbers trustworthy, shown
// identically under BOTH personas (Coach + Analyst) and the single-ticker read.
// Dataset type + calculation window are project constants (see DATA_SOURCE.md);
// holdings count + explanation source come from the report itself. The
// "How this was calculated" line is a native <details> disclosure — no JS.
import type { RiskExplanation } from "@/lib/types";

import styles from "./trust-strip.module.css";

const SOURCE_LABEL: Record<RiskExplanation["source"], string> = {
  model: "AI-written · every figure verified against the computed data",
  model_regenerated: "AI-written (regenerated after a guardrail catch) · figures verified",
  template_fallback: "Deterministic template (AI fell back) · figures verified",
  demo_fixture: "Sample explanation · every figure verified against the computed data",
};

interface TrustStripProps {
  source: RiskExplanation["source"];
  holdingsCount?: number;
  /** e.g. the number of holdings, or "single instrument" for the ticker view */
  scopeLabel?: string;
}

export function TrustStrip({ source, holdingsCount, scopeLabel }: TrustStripProps) {
  const scope = scopeLabel ?? (holdingsCount != null ? `${holdingsCount} holdings` : undefined);

  return (
    <div className={styles.strip}>
      <dl className={styles.facts}>
        <Fact label="Dataset" value="Synthetic, illustrative" />
        <Fact label="Window" value="504 trading days (~2y)" />
        {scope && <Fact label="Scope" value={scope} />}
        <Fact label="Explanation" value={SOURCE_LABEL[source]} />
      </dl>

      <details className={styles.how}>
        <summary className={styles.summary}>How this was calculated</summary>
        <div className={styles.body}>
          <p>
            Prices are a deterministic, seeded synthetic series (correlated geometric
            Brownian motion, seed 42) — not live market data, so results are fully
            reproducible. The risk math is real: covariance-based portfolio volatility,
            value-weighted top-3 concentration, and historical max drawdown, all computed
            on that series.
          </p>
          <p>
            The written explanation is generated by a guardrailed language model that may
            only restate figures the engine computed — it can never invent a number.
          </p>
        </div>
      </details>
    </div>
  );
}

function Fact({ label, value }: { label: string; value: string }) {
  return (
    <div className={styles.fact}>
      <dt className="caption">{label}</dt>
      <dd className={styles.factValue}>{value}</dd>
    </div>
  );
}
